# Generated by Django 4.0.4 on 2022-05-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='phoneModel',
        ),
    ]
